# advisor/gemini_service.py

try:
    import google.generativeai as genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False
    genai = None

from django.conf import settings
import json
from typing import Dict, List, Optional
import logging

from .training_examples import format_examples_for_prompt, get_examples_for_language
from .rule_based_ai import RuleBasedAI

logger = logging.getLogger(__name__)

class GeminiService:
    """
    Central service for communicating with Google Gemini API.
    Provides functions for test analysis, recommendation generation, and chat.
    """
    
    def __init__(self):
        """Initialize Gemini service"""
        # Check library availability first
        if not GEMINI_AVAILABLE:
            logger.warning("google-generativeai library not installed. Using fallback system.")
            self.model = None
            self.is_configured = False
            return
        
        try:
            api_key = settings.GEMINI_API_KEY
            if not api_key or api_key == 'your_api_key_here':
                logger.warning("GEMINI_API_KEY not configured. Using RuleBasedAI fallback.")
                self.model = None
                self.is_configured = False
            else:
                genai.configure(api_key=api_key)
                self.model = genai.GenerativeModel('gemini-pro')
                self.is_configured = True
                logger.info("Gemini API configured successfully")
        except Exception as e:
            logger.error(f"Error configuring Gemini: {str(e)}")
            self.model = None
            self.is_configured = False
        
        # Always initialize fallback AI
        self._fallback_ai = RuleBasedAI()
    
    def generate_content(self, prompt: str) -> str:
        """
        Generate content from Gemini.
        
        Args:
            prompt: The text to send to the model
            
        Returns:
            The text generated by Gemini
        """
        if not self.is_configured:
            return self._get_fallback_response(prompt)
        
        try:
            response = self.model.generate_content(prompt)
            return response.text
        except Exception as e:
            logger.error(f"Error generating content: {str(e)}")
            return self._get_fallback_response(prompt)
    
    def analyze_test_results(self, user_answers: Dict) -> Dict:
        """
        Analyze test results using Gemini.
        
        Args:
            user_answers: Dictionary containing the user's answers
            
        Returns:
            Dictionary containing the full analysis
        """
        if not self.is_configured:
            return self._get_fallback_analysis()
        
        # Build detailed analysis prompt
        prompt = self._build_analysis_prompt(user_answers)
        
        try:
            response = self.model.generate_content(prompt)
            analysis_text = response.text
            
            # Attempt to extract JSON from the response
            return self._parse_analysis_response(analysis_text)
            
        except Exception as e:
            logger.error(f"Error analyzing test results: {str(e)}")
            return self._get_fallback_analysis()
    
    def recommend_majors(self, personality_analysis: Dict, user_interests: List[str]) -> List[Dict]:
        """
        Recommend majors based on personality analysis.
        
        Args:
            personality_analysis: Personality analysis result
            user_interests: User's interests
            
        Returns:
            List of recommended majors with match percentages and reasons
        """
        if not self.is_configured:
            return self._get_fallback_recommendations()
        
        prompt = f"""
You are an expert academic advisor specializing in guiding students to choose the right university major.

Personality Analysis:
{json.dumps(personality_analysis, ensure_ascii=False, indent=2)}

Interests:
{', '.join(user_interests)}

Required:
Provide 5 recommended university majors with:
1. Major name
2. Match percentage (0-100%)
3. 3 clear reasons for the recommendation
4. Required skills
5. Expected career opportunities

Provide the response in JSON format as follows:
{{
  "recommendations": [
    {{
      "major_name": "Major Name",
      "match_percentage": 95,
      "reasons": ["reason 1", "reason 2", "reason 3"],
      "required_skills": ["skill 1", "skill 2"],
      "career_opportunities": ["job 1", "job 2"]
    }}
  ]
}}
"""
        
        try:
            response = self.model.generate_content(prompt)
            return self._parse_recommendations_response(response.text)
        except Exception as e:
            logger.error(f"Error generating recommendations: {str(e)}")
            return self._get_fallback_recommendations()
    
    def chat_response(self, message: str, context: Optional[Dict] = None) -> str:
        """
        Respond to a chat message from the user.
        
        Args:
            message: The user's message
            context: Context (user profile, conversation history, etc.)
            
        Returns:
            The AI's response
        """
        if not self.is_configured:
            return self._get_fallback_chat_response(message)
        
        # Build prompt with context
        prompt = self._build_chat_prompt(message, context)
        
        try:
            response = self.model.generate_content(prompt)
            return response.text
        except Exception as e:
            logger.error(f"Error in chat: {str(e)}")
            return self._get_fallback_chat_response(message)
    
    # === Helper Methods ===
    
    def _build_analysis_prompt(self, user_answers: Dict) -> str:
        """Build prompt for test result analysis with Few-Shot Examples"""
        
        # Detect language from data
        language = self._detect_language(user_answers)
        
        # Get training examples
        examples = format_examples_for_prompt(language, max_examples=2)
        
        if language == "arabic":
            prompt = f"""
You are an expert in personality analysis and career guidance for university students.

**Your Task:** Analyze the student's answers and provide accurate, personalized recommendations.

{examples}

Now, analyze the following student's answers using the same approach:

**Student Data:**
{json.dumps(user_answers, ensure_ascii=False, indent=2)}

**Required Analysis:**
1. **Personality Type**: Identify the dominant type (analytical, creative, social, organized, practical)
2. **Strengths**: List 5 specific strengths based on the answers
3. **Main Interests**: Identify the top 3 areas of interest
4. **Preferred Learning Style**: Brief description
5. **Suitable Study Environment**: Description of the ideal environment

**Response Format (JSON):**
{{
  "personality_type": "personality type",
  "strengths": ["strength 1", "strength 2", "strength 3", "strength 4", "strength 5"],
  "interests": ["interest 1", "interest 2", "interest 3"],
  "learning_style": "learning style",
  "suitable_environment": "description of suitable environment"
}}
"""
        else:  # English
            prompt = f"""
You are an expert in personality analysis and career guidance for university students.

**Your Task:** Analyze the student's answers and provide accurate, personalized recommendations.

{examples}

Now, analyze the following student's answers using the same approach:

**Student Data:**
{json.dumps(user_answers, ensure_ascii=False, indent=2)}

**Required Analysis:**
1. **Personality Type**: Identify the dominant type (analytical, creative, social, organized, practical)
2. **Strengths**: List 5 specific strengths based on the answers
3. **Main Interests**: Identify the top 3 areas of interest
4. **Preferred Learning Style**: Brief description
5. **Suitable Study Environment**: Description of the ideal environment

**Response Format (JSON):**
{{
  "personality_type": "personality type",
  "strengths": ["strength 1", "strength 2", "strength 3", "strength 4", "strength 5"],
  "interests": ["interest 1", "interest 2", "interest 3"],
  "learning_style": "learning style",
  "suitable_environment": "description of suitable environment"
}}
"""
        
        return prompt
    
    def _detect_language(self, data: Dict) -> str:
        """
        Detect language from data.
        """
        # Check dictionary keys
        data_str = json.dumps(data, ensure_ascii=False).lower()
        
        # Common Arabic keywords
        arabic_keywords = ['تحليلي', 'إبداعي', 'اجتماعي', 'علوم', 'هندسة', 'طب']
        # Common English keywords
        english_keywords = ['analytical', 'creative', 'social', 'science', 'engineering', 'medicine']
        
        arabic_count = sum(1 for word in arabic_keywords if word in data_str)
        english_count = sum(1 for word in english_keywords if word in data_str)
        
        return "arabic" if arabic_count > english_count else "english"
    
    def _build_chat_prompt(self, message: str, context: Optional[Dict]) -> str:
        """Build chat prompt with context"""
        context_str = ""
        if context:
            if 'user_profile' in context:
                context_str += f"\nStudent Info: {context['user_profile']}"
            if 'conversation_history' in context:
                context_str += f"\nConversation History: {context['conversation_history']}"
        
        prompt = f"""
You are a smart academic advisor specializing in helping students choose the right university major.

{context_str}

Student Message: {message}

Provide a helpful and encouraging response that assists the student in making their decision. Be friendly and professional.
"""
        return prompt
    
    def _parse_analysis_response(self, response_text: str) -> Dict:
        """Extract JSON from analysis response"""
        try:
            # Attempt to find JSON in the text
            start = response_text.find('{')
            end = response_text.rfind('}') + 1
            if start != -1 and end > start:
                json_str = response_text[start:end]
                return json.loads(json_str)
        except:
            pass
        
        # If failed, use response as plain text
        return {
            'personality_type': 'Balanced',
            'strengths': ['Ability to learn', 'Adaptability'],
            'interests': ['Diverse interests'],
            'learning_style': 'Flexible',
            'suitable_environment': response_text[:200]
        }
    
    def _parse_recommendations_response(self, response_text: str) -> List[Dict]:
        """Extract recommendations from response"""
        try:
            start = response_text.find('{')
            end = response_text.rfind('}') + 1
            if start != -1 and end > start:
                json_str = response_text[start:end]
                data = json.loads(json_str)
                return data.get('recommendations', [])
        except:
            pass
        
        return self._get_fallback_recommendations()
    
    # === Fallback Methods — delegate to RuleBasedAI for rich bilingual responses ===
    
    def _get_fallback_response(self, prompt: str) -> str:
        """Rich fallback using RuleBasedAI chat engine"""
        return self._fallback_ai.chat(prompt)
    
    def _get_fallback_analysis(self) -> Dict:
        """Rich fallback analysis using RuleBasedAI"""
        result = self._fallback_ai.analyze({})
        pa = result.get('personality_analysis', {})
        return {
            'personality_type': pa.get('personality_type', 'Balanced'),
            'strengths': pa.get('strengths', ['Continuous learning', 'Problem solving', 'Adaptability']),
            'interests': pa.get('top_interests', ['Technology', 'Science']),
            'learning_style': pa.get('learning_style', 'Flexible and diverse'),
            'suitable_environment': pa.get('suitable_environment', 'Diverse academic environment')
        }
    
    def _get_fallback_recommendations(self) -> List[Dict]:
        """Rich fallback recommendations — both Arabic & English majors"""
        return [
            {
                'major_name': 'Computer Science / علوم الحاسب',
                'match_percentage': 80,
                'reasons': ['Vital tech field / مجال تقني حيوي', 'Wide global career opportunities / فرص عالمية', 'Competitive salaries / رواتب تنافسية'],
                'required_skills': ['Programming', 'Logical thinking', 'Mathematics'],
                'career_opportunities': ['Software Engineer', 'Data Scientist', 'AI Engineer']
            },
            {
                'major_name': 'Business Administration / إدارة الأعمال',
                'match_percentage': 75,
                'reasons': ['Comprehensive field / مجال شامل', 'Universal applicability / تطبيق شامل', 'Leadership opportunities / فرص قيادية'],
                'required_skills': ['Planning', 'Communication', 'Leadership'],
                'career_opportunities': ['Manager', 'Entrepreneur', 'Business Analyst']
            },
            {
                'major_name': 'Medicine / الطب البشري',
                'match_percentage': 72,
                'reasons': ['Humanitarian + scientific / علم وإنسانية', 'High market demand / طلب سوق عال', 'Stable career / استقرار مهني'],
                'required_skills': ['Science', 'Empathy', 'Precision'],
                'career_opportunities': ['Doctor', 'Researcher', 'Medical Specialist']
            },
            {
                'major_name': 'Engineering / الهندسة',
                'match_percentage': 70,
                'reasons': ['Practical + analytical / عملي وتحليلي', 'Wide applications / تطبيقات واسعة', 'Innovation driven / مدفوع بالابتكار'],
                'required_skills': ['Mathematics', 'Physics', 'Problem solving'],
                'career_opportunities': ['Civil Engineer', 'Mechanical Engineer', 'Project Manager']
            },
            {
                'major_name': 'Graphic Design / التصميم الجرافيكي',
                'match_percentage': 68,
                'reasons': ['Creativity & skill / إبداع ومهارة', 'Growing digital market / سوق رقمي متنامي', 'Professional freedom / استقلالية مهنية'],
                'required_skills': ['Design tools', 'Creativity', 'Visual communication'],
                'career_opportunities': ['Designer', 'Brand Specialist', 'UI/UX Designer']
            },
        ]
    
    def _get_fallback_chat_response(self, message: str) -> str:
        """Rich bilingual fallback chat using RuleBasedAI"""
        return self._fallback_ai.chat(message)
