# Generated by Django 5.2.6 on 2026-03-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='personality_traits',
            field=models.CharField(help_text='Personality traits (comma-separated)', max_length=300),
        ),
    ]
